filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/*.log
    - /home/ec2-user/smstests/student_server.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "elk.digiorum.com:443"
  protocol: "https"
  space.id: logs

setup.template.name: "logs"
setup.template.pattern: "logs-*"
output.elasticsearch:
  hosts: ["https://es.digiorum.com:443"]
  index: "logs-%{+yyyy.MM.dd}"
  preset: balanced
  protocol: "https"
  username: "elk_user"
  password: "elk_pass"
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
