- hosts: testservers
  become: true
  tasks:

  - name: Import the Elastic GPG key
    ansible.builtin.rpm_key:
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Add Elastic yum repository
    ansible.builtin.yum_repository:
      name: elastic-8.x
      description: Elastic repository for 8.x packages
      baseurl: https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck: yes
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled: yes

  - name: Install Filebeat
    ansible.builtin.yum:
      name: filebeat
      state: latest

  - name: Template filebeat config file to /etc/filebeat/filebeat.yml
    ansible.builtin.template:
      src: filebeat_config.yml
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: '0644'

  - name: Run filebeat setup
    ansible.builtin.command: filebeat setup
    args:
      creates: /etc/filebeat/filebeat.yml

  - name: Enable and start filebeat service
    ansible.builtin.service:
      name: filebeat
      enabled: yes
      state: started
